#
# Parameters
# Common parameters for strategies
#

# Common signal periods
MA_P_VERYFAST = 9
MA_P_FAST = 12
MA_P_MED = 20
MA_P_MED2 = 21
MA_P_MED3 = 26
MA_P_SLOW = 50
MA_P_LONG = 100
MA_P_VERYLONG = 200

# SMA
SMA_2_CROSS_VERYFAST = (MA_P_VERYFAST, MA_P_MED)
SMA_2_CROSS_FAST = (MA_P_FAST, MA_P_MED2)
SMA_2_CROSS_MED = (MA_P_MED, MA_P_SLOW)
SMA_2_CROSS_SLOW = (MA_P_SLOW, MA_P_VERYLONG)

# EMA
EMA_2_CROSS_VERYFAST = (MA_P_VERYFAST, MA_P_MED2)
EMA_2_CROSS_FAST = (MA_P_FAST, MA_P_MED3)
EMA_2_CROSS_MED = (MA_P_MED3, MA_P_SLOW)
EMA_2_CROSS_SLOW = (MA_P_SLOW, MA_P_VERYLONG)

# Other
TRI_SMA_CROSS = (MA_P_FAST, MA_P_MED2, 34)

MOMENTUM_SWING = (MA_P_VERYFAST, MA_P_MED3, MA_P_VERYLONG)

MACD_FAST = (MA_P_FAST, MA_P_MED3, MA_P_VERYFAST)
MACD_SLOW = (MA_P_SLOW, MA_P_VERYLONG, 40)
