#
# Configurations for Downloads
#


#
# Yahoo
#

from collections import namedtuple

MapItem = namedtuple('MapItem', ['name', 'statement', 'code', 'priority', 'mult'])

YahooFinancialsConf = ['ticker', 'freq', 'currency', 'statement', 'date', 'code', 'value']
# YahooFinancialsMapping = [
#     MapItem('researchDevelopment', 'INC', 'ERAD', 0, 1.),
#     MapItem('effectOfAccountingCharges', 'INC', 'SFEE', 0, 1.),
#     MapItem('incomeBeforeTax', 'INC', 'EIBT', 0, 1.),
#     MapItem('minorityInterest', 'INC', 'CMIN', 0, 1.),
#     MapItem('netIncome', 'INC', 'NINC', 0, 1.),
#     MapItem('sellingGeneralAdministrative', 'INC', 'SSGA', 0, 1.),
#     MapItem('grossProfit', 'INC', 'SGRP', 0, 1.),
#     MapItem('ebit', 'INC', '', 0, 1.),
#     MapItem('operatingIncome', 'INC', '', 0, 1.),  # not SOPI!
#     MapItem('otherOperatingExpenses', 'INC', 'SOOE', 0, 1.),
#     MapItem('interestExpense', 'INC', 'STIE', 0, 1.),
#     MapItem('extraordinaryItems', 'INC', 'STXI', 0, 1.),
#     MapItem('nonRecurring', 'INC', '', 0, 1.),
#     MapItem('otherItems', 'INC', 'SONT', 0, 1.),
#     MapItem('incomeTaxExpense', 'INC', 'TTAX', 0, 1.),
#     MapItem('totalRevenue', 'INC', 'RTLR', 0, 1.),
#     MapItem('totalOperatingExpenses', 'INC', 'ETOE', 0, 1.),
#     MapItem('costOfRevenue', 'INC', 'SCOR', 0, 1.),
#     MapItem('totalOtherIncomeExpenseNet', 'INC', 'SOOE', 0, 1.),
#     MapItem('discontinuedOperations', 'INC', '', 0, 1.),
#     MapItem('netIncomeFromContinuingOps', 'INC', 'TIAT', 0, 1.),
#     MapItem('netIncomeApplicableToCommonShares', 'INC', 'XNIC', 0, 1.),
#     MapItem('intangibleAssets', 'BAL', 'SGRP', 0, 1.),
#     MapItem('totalLiab', 'BAL', 'LTLL', 0, 1.),
#     MapItem('totalStockholderEquity', 'BAL', 'QTLE', 0, 1.),
#     MapItem('deferredLongTermLiab', 'BAL', '', 0, 1.),
#     MapItem('otherCurrentLiab', 'BAL', 'SOCL', 0, 1.),
#     MapItem('totalAssets', 'BAL', 'ATOT', 0, 1.),
#     MapItem('commonStock', 'BAL', '', 0, 1.),
#     MapItem('otherCurrentAssets', 'BAL', 'SOCA', 0, 1.),
#     MapItem('retainedEarnings', 'BAL', 'QRED', 0, 1.),
#     MapItem('minorityInterest', 'BAL', 'CMIN', 0, 1.),
#     MapItem('otherLiab', 'BAL', 'SLTL', 0, 1.),
#     MapItem('goodWill', 'BAL', 'AGWI', 0, 1.),
#     MapItem('treasuryStock', 'BAL', 'QTSC', 0, 1.),
#     MapItem('otherAssets', 'BAL', 'SOAT', 0, 1.),
#     MapItem('cash', 'BAL', 'ACAE', 0, 1.),
#     MapItem('totalCurrentLiabilities', 'BAL', 'LTCL', 0, 1.),
#     MapItem('deferredLongTermAssetCharges', 'BAL', '', 0, 1.),
#     MapItem('shortLongTermDebt', 'BAL', '', 0, 1.),
#     MapItem('otherStockholderEquity', 'BAL', 'SOTE', 0, 1.),
#     MapItem('propertyPlantEquipment', 'BAL', 'APPN', 0, 1.),
#     MapItem('totalCurrentAssets', 'BAL', 'ATCA', 0, 1.),
#     MapItem('longTermInvestments', 'BAL', 'SINV', 0, 1.),
#     MapItem('netTangibleAssets', 'BAL', '0ANTA', 0, 1.),
#     MapItem('shortTermInvestments', 'BAL', 'ASTI', 0, 1.),
#     MapItem('netReceivables', 'BAL', 'ATRC', 0, 1.),
#     MapItem('longTermDebt', 'BAL', 'LLTD', 0, 1.),
#     MapItem('inventory', 'BAL', 'AITL', 0, 1.),
#     MapItem('accountsPayable', 'BAL', 'LAPB', 0, 1.),
#     MapItem('capitalSurplus', 'BAL', '', 0, 1.),
#     # NOTE: netIncome is renamed CFnetIncome to avoid clashing with Income statement
#     MapItem('changeToLiabilities', 'CAS', '0SCLB', 0, 1.),
#     MapItem('totalCashflowsFromInvestingActivities', 'CAS', 'ITLI', 0, 1.),
#     MapItem('repurchaseOfStock', 'CAS', '', 0, 1.),
#     MapItem('netBorrowings', 'CAS', 'FPRD', 0, 1.),
#     MapItem('totalCashFromFinancingActivities', 'CAS', 'FTLF', 0, 1.),
#     MapItem('changeToOperatingActivities', 'CAS', '', 0, 1.),
#     MapItem('netIncome', 'CAS', 'ONET', 0, 1.),
#     MapItem('changeInCash', 'CAS', 'SNCC', 0, 1.),
#     MapItem('effectOfExchangeRate', 'CAS', 'SFEE', 0, 1.),
#     MapItem('totalCashFromOperatingActivities', 'CAS', 'OTLO', 0, 1.),
#     MapItem('depreciation', 'CAS', 'SDED', 0, 1.),
#     MapItem('otherCashflowsFromInvestingActivities', 'CAS', 'SICF', 0, 1.),
#     MapItem('dividendsPaid', 'CAS', 'FCDP', 0, 1.),
#     MapItem('changeToInventory', 'CAS', '0SCIN', 0, 1.),
#     MapItem('changeToAccountReceivables', 'CAS', '0SCAR', 0, 1.),
#     MapItem('otherCashflowsFromFinancingActivities', 'CAS', 'SFCF', 0, 1.),
#     MapItem('changeToNetincome', 'CAS', '0SXCNI', 0, 1.),
#     MapItem('capitalExpenditures', 'CAS', 'SCEX', 0, 1.),
#     MapItem('investments', 'CAS', '', 0, 1.),
#     MapItem('issuanceOfStock', 'CAS', 'SFEE', 0, 1.),
#     MapItem('Amortization', 'TS', '', 0, 1.),
#     MapItem('AmortizationOfIntangiblesIncomeStatement', 'TS', '', 0, 1.),
#     MapItem('AverageDilutionEarnings', 'TS', '', 0, 1.),
#     MapItem('BasicAccountingChange', 'TS', '', 0, 1.),
#     MapItem('BasicAverageShares', 'TS', 'QTCO', 0, 1.),
#     MapItem('BasicContinuousOperations', 'TS', '', 0, 1.),
#     MapItem('BasicDiscontinuousOperations', 'TS', '', 0, 1.),
#     MapItem('BasicEPS', 'TS', '0BEPS', 0, 1.),
#     MapItem('BasicEPSOtherGainsLosses', 'TS', '', 0, 1.),
#     MapItem('BasicExtraordinary', 'TS', '', 0, 1.),
#     MapItem('CededPremiums', 'TS', '', 0, 1.),
#     MapItem('ContinuingAndDiscontinuedBasicEPS', 'TS', '', 0, 1.),
#     MapItem('ContinuingAndDiscontinuedDilutedEPS', 'TS', '', 0, 1.),
#     MapItem('CostOfRevenue', 'TS', '', 0, 1.),
#     MapItem('CreditCard', 'TS', '', 0, 1.),
#     MapItem('CreditLossesProvision', 'TS', '', 0, 1.),
#     MapItem('DDACostofRevenue', 'TS', '', 0, 1.),
#     MapItem('DepletionIncomeStatement', 'TS', '', 0, 1.),
#     MapItem('DepreciationAmortizationDepletionIncomeStatement', 'TS', '', 0, 1.),
#     MapItem('DepreciationAndAmortizationInIncomeStatement', 'TS', '', 0, 1.),
#     MapItem('DepreciationIncomeStatement', 'TS', '', 0, 1.),
#     MapItem('DilutedAccountingChange', 'TS', '', 0, 1.),
#     MapItem('DilutedAverageShares', 'TS', 'SDWS', 0, 1.),
#     MapItem('DilutedContinuousOperations', 'TS', '', 0, 1.),
#     MapItem('DilutedDiscontinuousOperations', 'TS', '', 0, 1.),
#     MapItem('DilutedEPS', 'TS', '0DEPS', 0, 1.),
#     MapItem('DilutedEPSOtherGainsLosses', 'TS', '', 0, 1.),
#     MapItem('DilutedExtraordinary', 'TS', '', 0, 1.),
#     MapItem('DilutedNIAvailtoComStockholders', 'TS', '', 0, 1.),
#     MapItem('DividendIncome', 'TS', '', 0, 1.),
#     MapItem('DividendPerShare', 'TS', '', 0, 1.),
#     MapItem('earnings', 'TS', '', 0, 1.),
#     MapItem('EarningsFromEquityInterest', 'TS', '', 0, 1.),
#     MapItem('EarningsFromEquityInterestNetOfTax', 'TS', '', 0, 1.),
#     MapItem('EBIT', 'TS', '', 0, 1.),
#     MapItem('EBITDA', 'TS', '', 0, 1.),
#     MapItem('EPSactual', 'TS', '', 0, 1.),
#     MapItem('EPSestimate', 'TS', '', 0, 1.),
#     MapItem('Equipment', 'TS', '', 0, 1.),
#     MapItem('ExciseTaxes', 'TS', '', 0, 1.),
#     MapItem('ExplorationDevelopmentAndMineralPropertyLeaseExpenses', 'TS', '', 0, 1.),
#     MapItem('FeesandCommissionExpense', 'TS', '', 0, 1.),
#     MapItem('FeesandCommissionIncome', 'TS', '', 0, 1.),
#     MapItem('FeesAndCommissions', 'TS', '', 0, 1.),
#     MapItem('Fuel', 'TS', '', 0, 1.),
#     MapItem('FuelAndPurchasePower', 'TS', '', 0, 1.),
#     MapItem('ForeignExchangeTradingGains', 'TS', '', 0, 1.),
#     MapItem('GainLossonSaleofAssets', 'TS', '', 0, 1.),
#     MapItem('GainOnSaleOfBusiness', 'TS', '', 0, 1.),
#     MapItem('GainonSaleofInvestmentProperty', 'TS', '', 0, 1.),
#     MapItem('GainonSaleofLoans', 'TS', '', 0, 1.),
#     MapItem('GainOnSaleOfPPE', 'TS', '', 0, 1.),
#     MapItem('GainOnSaleOfSecurity', 'TS', '', 0, 1.),
#     MapItem('GeneralAndAdministrativeExpense', 'TS', '', 0, 1.),
#     MapItem('GrossPremiumsWritten', 'TS', '', 0, 1.),
#     MapItem('GrossProfit', 'TS', '', 0, 1.),
#     MapItem('ImpairmentOfCapitalAssets', 'TS', '', 0, 1.),
#     MapItem('IncreaseDecreaseInNetUnearnedPremiumReserves', 'TS', '', 0, 1.),
#     MapItem('IncomefromAssociatesandOtherParticipatingInterests', 'TS', '', 0, 1.),
#     MapItem('InsuranceAndClaims', 'TS', '', 0, 1.),
#     MapItem('InterestExpense', 'TS', '', 0, 1.),
#     MapItem('InterestExpenseForDeposit', 'TS', '', 0, 1.),
#     MapItem('InterestExpenseForFederalFundsSoldAndSecuritiesPurchaseUnderAgreementsToResell', 'TS', '', 0, 1.),
#     MapItem('InterestExpenseForLongTermDebtAndCapitalSecurities', 'TS', '', 0, 1.),
#     MapItem('InterestExpenseForShortTermDebt', 'TS', '', 0, 1.),
#     MapItem('InterestExpenseNonOperating', 'TS', '', 0, 1.),
#     MapItem('InterestIncome', 'TS', '', 0, 1.),
#     MapItem('InterestIncomeAfterProvisionForLoanLoss', 'TS', '', 0, 1.),
#     MapItem('InterestIncomeFromDeposits', 'TS', '', 0, 1.),
#     MapItem('InterestIncomeFromFederalFundsSoldAndSecuritiesPurchaseUnderAgreementsToResell', 'TS', '', 0, 1.),
#     MapItem('InterestIncomeFromLeases', 'TS', '', 0, 1.),
#     MapItem('InterestIncomeFromLoans', 'TS', '', 0, 1.),
#     MapItem('InterestIncomeFromLoansAndLease', 'TS', '', 0, 1.),
#     MapItem('InterestIncomeFromSecurities', 'TS', '', 0, 1.),
#     MapItem('InterestIncomeNonOperating', 'TS', '', 0, 1.),
#     MapItem('InvestmentBankingProfit', 'TS', '', 0, 1.),
#     MapItem('LossonExtinguishmentofDebt', 'TS', '', 0, 1.),
#     MapItem('MaintenanceAndRepairs', 'TS', '', 0, 1.),
#     MapItem('MinorityInterests', 'TS', '', 0, 1.),
#     MapItem('NetIncome', 'TS', 'NINC', 1, 1.),
#     MapItem('NetIncomeCommonStockholders', 'TS', '', 0, 1.),
#     MapItem('NetIncomeContinuousOperations', 'TS', 'TIAT', 1, 1.),
#     MapItem('NetIncomeDiscontinuousOperations', 'TS', '', 0, 1.),
#     MapItem('NetIncomeExtraordinary', 'TS', '', 0, 1.),
#     MapItem('NetIncomeFromContinuingAndDiscontinuedOperation', 'TS', '', 0, 1.),
#     MapItem('NetIncomeFromContinuingOperationNetMinorityInterest', 'TS', '', 0, 1.),
#     MapItem('NetIncomeFromTaxLossCarryforward', 'TS', '', 0, 1.),
#     MapItem('NetIncomeIncludingNoncontrollingInterests', 'TS', '', 0, 1.),
#     MapItem('NetInterestIncome', 'TS', '', 0, 1.),
#     MapItem('NetInvestmentIncome', 'TS', '', 0, 1.),
#     MapItem('NetNonOperatingInterestIncomeExpense', 'TS', '', 0, 1.),
#     MapItem('NetOccupancyExpense', 'TS', '', 0, 1.),
#     MapItem('NetPolicyholderBenefitsAndClaims', 'TS', '', 0, 1.),
#     MapItem('NetPremiumsWritten', 'TS', '', 0, 1.),
#     MapItem('NetRealizedGainLossOnInvestments', 'TS', '', 0, 1.),
#     MapItem('NonInterestExpense', 'TS', '', 0, 1.),
#     MapItem('NonInterestIncome', 'TS', '', 0, 1.),
#     MapItem('NormalizedBasicEPS', 'TS', '0NBEP', 0, 1.),
#     MapItem('NormalizedDilutedEPS', 'TS', 'VDES', 0, 1.),
#     MapItem('NormalizedEBITDA', 'TS', '0NEBD', 0, 1.),
#     MapItem('NormalizedIncome', 'TS', '', 0, 1.),
#     MapItem('OccupancyAndEquipment', 'TS', '', 0, 1.),
#     MapItem('OperatingExpense', 'TS', '', 0, 1.),
#     MapItem('OperatingIncome', 'TS', '', 0, 1.),
#     MapItem('OperatingRevenue', 'TS', '', 0, 1.),
#     MapItem('OperationAndMaintenance', 'TS', '', 0, 1.),
#     MapItem('OtherCostofRevenue', 'TS', '', 0, 1.),
#     MapItem('OtherCustomerServices', 'TS', '', 0, 1.),
#     MapItem('OtherGandA', 'TS', '', 0, 1.),
#     MapItem('OtherIncomeExpense', 'TS', '', 0, 1.),
#     MapItem('OtherInterestExpense', 'TS', '', 0, 1.),
#     MapItem('OtherInterestIncome', 'TS', '', 0, 1.),
#     MapItem('OtherNonInterestExpense', 'TS', '', 0, 1.),
#     MapItem('OtherNonInterestIncome', 'TS', '', 0, 1.),
#     MapItem('OtherNonOperatingIncomeExpenses', 'TS', '', 0, 1.),
#     MapItem('OtherOperatingExpenses', 'TS', '', 0, 1.),
#     MapItem('OtherSpecialCharges', 'TS', '', 0, 1.),
#     MapItem('OtherTaxes', 'TS', '', 0, 1.),
#     MapItem('OtherunderPreferredStockDividend', 'TS', '', 0, 1.),
#     MapItem('PolicyAcquisitionExpense', 'TS', '', 0, 1.),
#     MapItem('PreferredStockDividends', 'TS', '', 0, 1.),
#     MapItem('PretaxIncome', 'TS', 'EIBT', 1, 1.),
#     MapItem('ProfessionalExpenseAndContractServicesExpense', 'TS', '', 0, 1.),
#     MapItem('ProvisionForDoubtfulAccounts', 'TS', '', 0, 1.),
#     MapItem('ReconciledCostOfRevenue', 'TS', '', 0, 1.),
#     MapItem('ReconciledDepreciation', 'TS', '', 0, 1.),
#     MapItem('RentAndLandingFees', 'TS', '', 0, 1.),
#     MapItem('RentandLandingFeesCostofRevenue', 'TS', '', 0, 1.),
#     MapItem('RentExpenseSupplemental', 'TS', '', 0, 1.),
#     MapItem('ReportedNormalizedBasicEPS', 'TS', '', 0, 1.),
#     MapItem('ReportedNormalizedDilutedEPS', 'TS', '', 0, 1.),
#     MapItem('ResearchAndDevelopment', 'TS', '', 0, 1.),
#     MapItem('RestructuringAndMergernAcquisition', 'TS', '', 0, 1.),
#     MapItem('SalariesAndWages', 'TS', '', 0, 1.),
#     MapItem('SecuritiesActivities', 'TS', '', 0, 1.),
#     MapItem('SecuritiesAmortization', 'TS', '', 0, 1.),
#     MapItem('SellingAndMarketingExpense', 'TS', '', 0, 1.),
#     MapItem('SellingGeneralAndAdministration', 'TS', '', 0, 1.),
#     MapItem('ServiceChargeOnDepositorAccounts', 'TS', '', 0, 1.),
#     MapItem('SpecialIncomeCharges', 'TS', '', 0, 1.),
#     MapItem('TaxEffectOfUnusualItems', 'TS', '', 0, 1.),
#     MapItem('TaxLossCarryforwardBasicEPS', 'TS', '', 0, 1.),
#     MapItem('TaxLossCarryforwardDilutedEPS', 'TS', '', 0, 1.),
#     MapItem('TaxProvision', 'TS', '', 0, 1.),
#     MapItem('TaxRateForCalcs', 'TS', '0TXR', 0, 1.),
#     MapItem('TotalExpenses', 'TS', '', 0, 1.),
#     MapItem('TotalMoneyMarketInvestments', 'TS', '', 0, 1.),
#     MapItem('TotalOperatingIncomeAsReported', 'TS', 'SOPI', 0, 1.),
#     MapItem('TotalOtherFinanceCost', 'TS', '', 0, 1.),
#     MapItem('TotalPremiumsEarned', 'TS', '', 0, 1.),
#     MapItem('TotalRevenue', 'TS', '', 0, 1.),
#     MapItem('TotalUnusualItems', 'TS', '', 0, 1.),
#     MapItem('TotalUnusualItemsExcludingGoodwill', 'TS', '', 0, 1.),
#     MapItem('TradingGainLoss', 'TS', '', 0, 1.),
#     MapItem('TrustFeesbyCommissions', 'TS', '', 0, 1.),
#     MapItem('WriteOff', 'TS', '', 0, 1.)
# ]

YahooFinancialsMapping = [
    MapItem('AccountsPayable', 'BAL', 'ACCPAY', 0, 1.),
    MapItem('AccountsReceivable', 'BAL', 'ACCREC', 0, 1.),
    MapItem('AccruedInterestReceivable', 'BAL', 'ACINRC', 0, 1.),
    MapItem('AccumulatedDepreciation', 'BAL', 'ACCDEP', 0, 1.),
    MapItem('AdditionalPaidInCapital', 'BAL', 'ADDPIC', 0, 1.),
    MapItem('AdjustedGeographySegmentData', 'CAS', 'ADJGSD', 0, 1.),
    MapItem('AllowanceForDoubtfulAccountsReceivable', 'BAL', 'ALDARC', 0, 1.),
    MapItem('Amortization', 'INC', 'AMORTZ', 0, 1.),
    MapItem('AmortizationCashFlow', 'CAS', 'AMORCF', 0, 1.),
    MapItem('AmortizationOfIntangibles', 'CAS', 'AMOINT', 0, 1.),
    MapItem('AmortizationOfIntangiblesIncomeStatement', 'INC', 'AMOIIS', 0, 1.),
    MapItem('AmortizationOfSecurities', 'CAS', 'AMOSEC', 0, 1.),
    MapItem('AssetImpairmentCharge', 'CAS', 'ASIMCH', 0, 1.),
    MapItem('AssetsHeldForSaleCurrent', 'BAL', 'ASHFSC', 0, 1.),
    MapItem('AvailableForSaleSecurities', 'BAL', 'AVFSSE', 0, 1.),
    MapItem('AverageDilutionEarnings', 'INC', 'AVGDEA', 0, 1.),
    MapItem('BasicAccountingChange', 'INC', 'BACCCH', 0, 1.),
    MapItem('BasicAverageShares', 'INC', 'BAVGSH', 0, 1.),
    MapItem('BasicContinuousOperations', 'INC', 'BCONOP', 0, 1.),
    MapItem('BasicDiscontinuousOperations', 'INC', 'BDCNOP', 0, 1.),
    MapItem('BasicEPS', 'INC', 'BASEPS', 0, 1.),
    MapItem('BasicEPSOtherGainsLosses', 'INC', 'BAEOGL', 0, 1.),
    MapItem('BasicExtraordinary', 'INC', 'BASEXT', 0, 1.),
    MapItem('BeginningCashPosition', 'CAS', 'BECHPO', 0, 1.),
    MapItem('BuildingsAndImprovements', 'BAL', 'BUIIMP', 0, 1.),
    MapItem('CapitalExpenditure', 'CAS', 'CAPEXP', 0, 1.),
    MapItem('CapitalExpenditureReported', 'CAS', 'CAPEXR', 0, 1.),
    MapItem('CapitalLeaseObligations', 'BAL', 'CAPLOB', 0, 1.),
    MapItem('CapitalStock', 'BAL', 'CAPSTK', 0, 1.),
    MapItem('CashAndCashEquivalents', 'BAL', 'CHCHEQ', 0, 1.),
    MapItem('CashCashEquivalentsAndShortTermInvestments', 'BAL', 'CCESTI', 0, 1.),
    MapItem('CashDividendsPaid', 'CAS', 'CHDIVP', 0, 1.),
    MapItem('CashEquivalents', 'BAL', 'CHEQUI', 0, 1.),
    MapItem('CashFinancial', 'BAL', 'CHFINS', 0, 1.),
    MapItem('CashFlowFromContinuingFinancingActivities', 'CAS', 'CFWCFA', 0, 1.),
    MapItem('CashFlowFromContinuingInvestingActivities', 'CAS', 'CFWCIA', 0, 1.),
    MapItem('CashFlowFromContinuingOperatingActivities', 'CAS', 'CFWCOA', 0, 1.),
    MapItem('CashFlowFromDiscontinuedOperation', 'CAS', 'CFWDOP', 0, 1.),
    MapItem('CashFlowsfromusedinOperatingActivitiesDirect', 'CAS', 'CFWUOA', 0, 1.),
    MapItem('CashFromDiscontinuedFinancingActivities', 'CAS', 'CFWDFA', 0, 1.),
    MapItem('CashFromDiscontinuedInvestingActivities', 'CAS', 'CFWDIA', 0, 1.),
    MapItem('CashFromDiscontinuedOperatingActivities', 'CAS', 'CFWDOA', 0, 1.),
    MapItem('ChangeInAccountPayable', 'CAS', 'CHACPY', 0, 1.),
    MapItem('ChangeInAccruedExpense', 'CAS', 'CHAREX', 0, 1.),
    MapItem('ChangeInCashSupplementalAsReported', 'CAS', 'CHCSAR', 0, 1.),
    MapItem('ChangeInDividendPayable', 'CAS', 'CHDVPY', 0, 1.),
    MapItem('ChangeInIncomeTaxPayable', 'CAS', 'CHITPY', 0, 1.),
    MapItem('ChangeInInterestPayable', 'CAS', 'CHINPY', 0, 1.),
    MapItem('ChangeInInventory', 'CAS', 'CHINVT', 0, 1.),
    MapItem('ChangeInOtherCurrentAssets', 'CAS', 'CHOCAS', 0, 1.),
    MapItem('ChangeInOtherCurrentLiabilities', 'CAS', 'CHOCLB', 0, 1.),
    MapItem('ChangeInOtherWorkingCapital', 'CAS', 'CHOWCP', 0, 1.),
    MapItem('ChangeInPayable', 'CAS', 'CHPYBL', 0, 1.),
    MapItem('ChangeInPayablesAndAccruedExpense', 'CAS', 'CHPAEX', 0, 1.),
    MapItem('ChangeInPrepaidAssets', 'CAS', 'CHPRAS', 0, 1.),
    MapItem('ChangeInReceivables', 'CAS', 'CHRECV', 0, 1.),
    MapItem('ChangeInTaxPayable', 'CAS', 'CHTXPY', 0, 1.),
    MapItem('ChangeInWorkingCapital', 'CAS', 'CHWKCP', 0, 1.),
    MapItem('ChangesInAccountReceivables', 'CAS', 'CHACRC', 0, 1.),
    MapItem('ChangesInCash', 'CAS', 'CHCASH', 0, 1.),
    MapItem('ClassesofCashPayments', 'CAS', 'CLCAPY', 0, 1.),
    MapItem('ClassesofCashReceiptsfromOperatingActivities', 'CAS', 'CLCROA', 0, 1.),
    MapItem('CommercialPaper', 'BAL', 'COMPAP', 0, 1.),
    MapItem('CommonStock', 'BAL', 'CSTOCK', 0, 1.),
    MapItem('CommonStockDividendPaid', 'CAS', 'CSTDVP', 0, 1.),
    MapItem('CommonStockEquity', 'BAL', 'CSTEQT', 0, 1.),
    MapItem('CommonStockIssuance', 'CAS', 'CSTISS', 0, 1.),
    MapItem('CommonStockPayments', 'CAS', 'CSTPAY', 0, 1.),
    MapItem('ConstructionInProgress', 'BAL', 'CNSTIP', 0, 1.),
    MapItem('ContinuingAndDiscontinuedBasicEPS', 'INC', 'CNDCBE', 0, 1.),
    MapItem('ContinuingAndDiscontinuedDilutedEPS', 'INC', 'CNDCDE', 0, 1.),
    MapItem('CostOfRevenue', 'INC', 'CSTREV', 0, 1.),
    MapItem('CurrentAccruedExpenses', 'BAL', 'CUACEX', 0, 1.),
    MapItem('CurrentAssets', 'BAL', 'CUASST', 0, 1.),
    MapItem('CurrentCapitalLeaseObligation', 'BAL', 'CUCLOB', 0, 1.),
    MapItem('CurrentDebt', 'BAL', 'CUDEBT', 0, 1.),
    MapItem('CurrentDebtAndCapitalLeaseObligation', 'BAL', 'CUDCLO', 0, 1.),
    MapItem('CurrentDeferredAssets', 'BAL', 'CUDFAS', 0, 1.),
    MapItem('CurrentDeferredLiabilities', 'BAL', 'CUDFLB', 0, 1.),
    MapItem('CurrentDeferredRevenue', 'BAL', 'CUDFRV', 0, 1.),
    MapItem('CurrentDeferredTaxesAssets', 'BAL', 'CUDFTA', 0, 1.),
    MapItem('CurrentDeferredTaxesLiabilities', 'BAL', 'CUDFTL', 0, 1.),
    MapItem('CurrentLiabilities', 'BAL', 'CULIAB', 0, 1.),
    MapItem('CurrentNotesPayable', 'BAL', 'CUNTPY', 0, 1.),
    MapItem('CurrentProvisions', 'BAL', 'CUPROV', 0, 1.),
    MapItem('DeferredIncomeTax', 'CAS', 'DFINTX', 0, 1.),
    MapItem('DeferredTax', 'CAS', 'DFRTAX', 0, 1.),
    MapItem('DefinedPensionBenefit', 'BAL', 'DFRPBN', 0, 1.),
    MapItem('Depletion', 'CAS', 'DEPLET', 0, 1.),
    MapItem('DepletionIncomeStatement', 'INC', 'DEPINS', 0, 1.),
    MapItem('Depreciation', 'CAS', 'DEPREC', 0, 1.),
    MapItem('DepreciationAmortizationDepletion', 'CAS', 'DRAMDL', 0, 1.),
    MapItem('DepreciationAmortizationDepletionIncomeStatement', 'INC', 'DPADIS', 0, 1.),
    MapItem('DepreciationAndAmortization', 'CAS', 'DPAMOR', 0, 1.),
    MapItem('DepreciationAndAmortizationInIncomeStatement', 'INC', 'DPAMIS', 0, 1.),
    MapItem('DepreciationIncomeStatement', 'INC', 'DPINCS', 0, 1.),
    MapItem('DerivativeProductLiabilities', 'BAL', 'DRPRLB', 0, 1.),
    MapItem('DilutedAccountingChange', 'INC', 'DLACCH', 0, 1.),
    MapItem('DilutedContinuousOperations', 'INC', 'DLCNOP', 0, 1.),
    MapItem('DilutedDiscontinuousOperations', 'INC', 'DLDCOP', 0, 1.),
    MapItem('DilutedEPS', 'INC', 'DLDEPS', 0, 1.),
    MapItem('DilutedEPSOtherGainsLosses', 'INC', 'DLEOGL', 0, 1.),
    MapItem('DilutedExtraordinary', 'INC', 'DLEXTR', 0, 1.),
    MapItem('DilutedNIAvailtoComStockholders', 'INC', 'DLNIAC', 0, 1.),
    MapItem('DividendPaidCFO', 'CAS', 'DVPCFO', 0, 1.),
    MapItem('DividendPerShare', 'INC', 'DVPSHR', 0, 1.),
    MapItem('DividendReceivedCFO', 'CAS', 'DVRCFO', 0, 1.),
    MapItem('DividendsPaidDirect', 'CAS', 'DVPDDR', 0, 1.),
    MapItem('DividendsPayable', 'BAL', 'DVPAYB', 0, 1.),
    MapItem('DividendsReceivedCFI', 'CAS', 'DVRCFI', 0, 1.),
    MapItem('DividendsReceivedDirect', 'CAS', 'DVRVDR', 0, 1.),
    MapItem('DomesticSales', 'CAS', 'DMSALE', 0, 1.),
    MapItem('DuefromRelatedPartiesCurrent', 'BAL', 'DFRPCU', 0, 1.),
    MapItem('DuefromRelatedPartiesNonCurrent', 'BAL', 'DFRPNC', 0, 1.),
    MapItem('DuetoRelatedPartiesCurrent', 'BAL', 'DTRPCU', 0, 1.),
    MapItem('DuetoRelatedPartiesNonCurrent', 'BAL', 'DTRPNC', 0, 1.),
    MapItem('EarningsFromEquityInterest', 'INC', 'EFEQIT', 0, 1.),
    MapItem('EarningsFromEquityInterestNetOfTax', 'INC', 'EFEINT', 0, 1.),
    MapItem('EarningsLossesFromEquityInvestments', 'CAS', 'ELFEQI', 0, 1.),
    MapItem('EBIT', 'INC', 'EBITXX', 0, 1.),
    MapItem('EBITDA', 'INC', 'EBITDA', 0, 1.),
    MapItem('EffectOfExchangeRateChanges', 'CAS', 'EEXRCH', 0, 1.),
    MapItem('EmployeeBenefits', 'BAL', 'EMPBEN', 0, 1.),
    MapItem('EndCashPosition', 'CAS', 'ENDCHP', 0, 1.),
    MapItem('EnterprisesValueEBITDARatio', 'TS', 'ETVEDR', 0, 1.),
    MapItem('EnterprisesValueRevenueRatio', 'TS', 'ETVRVR', 0, 1.),
    MapItem('EnterpriseValue', 'TS', 'ETVALE', 0, 1.),
    MapItem('ExcessTaxBenefitFromStockBasedCompensation', 'CAS', 'ETBSBC', 0, 1.),
    MapItem('ExciseTaxes', 'INC', 'EXSTAX', 0, 1.),
    MapItem('FinancialAssets', 'BAL', 'FINAST', 0, 1.),
    MapItem('FinancialAssetsDesignatedasFairValueThroughProfitorLossTotal', 'BAL', 'FAFVPL', 0, 1.),
    MapItem('FinancingCashFlow', 'CAS', 'FINCFW', 0, 1.),
    MapItem('FinishedGoods', 'BAL', 'FINGOO', 0, 1.),
    MapItem('FixedAssetsRevaluationReserve', 'BAL', 'FXARVR', 0, 1.),
    MapItem('ForeignCurrencyTranslationAdjustments', 'BAL', 'FCTADJ', 0, 1.),
    MapItem('ForeignSales', 'CAS', 'FSALES', 0, 1.),
    MapItem('ForwardPeRatio', 'TS', 'FWDPER', 0, 1.),
    MapItem('FreeCashFlow', 'CAS', 'FRCHFL', 0, 1.),
    MapItem('GainLossOnInvestmentSecurities', 'CAS', 'GLOISC', 0, 1.),
    MapItem('GainLossOnSaleOfBusiness', 'CAS', 'GLOSOB', 0, 1.),
    MapItem('GainLossOnSaleOfPPE', 'CAS', 'GLOSOP', 0, 1.),
    MapItem('GainOnSaleOfBusiness', 'INC', 'GOSBUS', 0, 1.),
    MapItem('GainOnSaleOfPPE', 'INC', 'GOSPPE', 0, 1.),
    MapItem('GainOnSaleOfSecurity', 'INC', 'GOSSEC', 0, 1.),
    MapItem('GainsLossesNotAffectingRetainedEarnings', 'BAL', 'GLNARE', 0, 1.),
    MapItem('GeneralAndAdministrativeExpense', 'INC', 'GAEXPS', 0, 1.),
    MapItem('GeneralPartnershipCapital', 'BAL', 'GPAEXP', 0, 1.),
    MapItem('Goodwill', 'BAL', 'GDWILL', 0, 1.),
    MapItem('GoodwillAndOtherIntangibleAssets', 'BAL', 'GWOINA', 0, 1.),
    MapItem('GrossAccountsReceivable', 'BAL', 'GACCRV', 0, 1.),
    MapItem('GrossPPE', 'BAL', 'GSSPPE', 0, 1.),
    MapItem('GrossProfit', 'INC', 'GSSPFT', 0, 1.),
    MapItem('HedgingAssetsCurrent', 'BAL', 'HDASCU', 0, 1.),
    MapItem('HeldToMaturitySecurities', 'BAL', 'HEMSEC', 0, 1.),
    MapItem('ImpairmentOfCapitalAssets', 'INC', 'IMPCAS', 0, 1.),
    MapItem('IncomeTaxPaidSupplementalData', 'CAS', 'INCTPD', 0, 1.),
    MapItem('IncomeTaxPayable', 'BAL', 'INCTPY', 0, 1.),
    MapItem('InsuranceAndClaims', 'INC', 'INSCLM', 0, 1.),
    MapItem('InterestExpense', 'INC', 'INTEXP', 0, 1.),
    MapItem('InterestExpenseNonOperating', 'INC', 'INTENO', 0, 1.),
    MapItem('InterestIncome', 'INC', 'INTINC', 0, 1.),
    MapItem('InterestIncomeNonOperating', 'INC', 'INTINO', 0, 1.),
    MapItem('InterestPaidCFF', 'CAS', 'INTPCF', 0, 1.),
    MapItem('InterestPaidCFO', 'CAS', 'INTPCO', 0, 1.),
    MapItem('InterestPaidDirect', 'CAS', 'INTPDI', 0, 1.),
    MapItem('InterestPaidSupplementalData', 'CAS', 'INTPSD', 0, 1.),
    MapItem('InterestPayable', 'BAL', 'INTPAY', 0, 1.),
    MapItem('InterestReceivedCFI', 'CAS', 'INTRCI', 0, 1.),
    MapItem('InterestReceivedCFO', 'CAS', 'INTRCO', 0, 1.),
    MapItem('InterestReceivedDirect', 'CAS', 'INTRDI', 0, 1.),
    MapItem('InventoriesAdjustmentsAllowances', 'BAL', 'IVTAAL', 0, 1.),
    MapItem('Inventory', 'BAL', 'IVTORY', 0, 1.),
    MapItem('InvestedCapital', 'BAL', 'INVCAP', 0, 1.),
    MapItem('InvestingCashFlow', 'CAS', 'INVCSF', 0, 1.),
    MapItem('InvestmentinFinancialAssets', 'BAL', 'INVFAS', 0, 1.),
    MapItem('InvestmentProperties', 'BAL', 'INVPRP', 0, 1.),
    MapItem('InvestmentsAndAdvances', 'BAL', 'INVADV', 0, 1.),
    MapItem('InvestmentsinAssociatesatCost', 'BAL', 'INVASC', 0, 1.),
    MapItem('InvestmentsinJointVenturesatCost', 'BAL', 'INVJVC', 0, 1.),
    MapItem('InvestmentsInOtherVenturesUnderEquityMethod', 'BAL', 'INVOVE', 0, 1.),
    MapItem('InvestmentsinSubsidiariesatCost', 'BAL', 'INVSBC', 0, 1.),
    MapItem('IssuanceOfCapitalStock', 'CAS', 'ISCPST', 0, 1.),
    MapItem('IssuanceOfDebt', 'CAS', 'ISDEBT', 0, 1.),
    MapItem('LandAndImprovements', 'BAL', 'LNDIMP', 0, 1.),
    MapItem('Leases', 'BAL', 'LEASES', 0, 1.),
    MapItem('LiabilitiesHeldforSaleNonCurrent', 'BAL', 'LBHSNC', 0, 1.),
    MapItem('LimitedPartnershipCapital', 'BAL', 'LMPAPC', 0, 1.),
    MapItem('LineOfCredit', 'BAL', 'LNCRED', 0, 1.),
    MapItem('LoansReceivable', 'BAL', 'LORECV', 0, 1.),
    MapItem('LongTermCapitalLeaseObligation', 'BAL', 'LTCLOB', 0, 1.),
    MapItem('LongTermDebt', 'BAL', 'LTDEBT', 0, 1.),
    MapItem('LongTermDebtAndCapitalLeaseObligation', 'BAL', 'LTDCLO', 0, 1.),
    MapItem('LongTermDebtIssuance', 'CAS', 'LTDBIS', 0, 1.),
    MapItem('LongTermDebtPayments', 'CAS', 'LTDBPY', 0, 1.),
    MapItem('LongTermEquityInvestment', 'BAL', 'LTEQIN', 0, 1.),
    MapItem('LongTermProvisions', 'BAL', 'LTPROV', 0, 1.),
    MapItem('MachineryFurnitureEquipment', 'BAL', 'MACFEQ', 0, 1.),
    MapItem('MarketCap', 'TS', 'MKTCAP', 0, 1.),
    MapItem('MinimumPensionLiabilities', 'BAL', 'MIPELB', 0, 1.),
    MapItem('MinorityInterest', 'BAL', 'MININB', 0, 1.),
    MapItem('MinorityInterests', 'INC', 'MININI', 0, 1.),
    MapItem('NetBusinessPurchaseAndSale', 'CAS', 'NBPUSL', 0, 1.),
    MapItem('NetCommonStockIssuance', 'CAS', 'NCSTIS', 0, 1.),
    MapItem('NetDebt', 'BAL', 'NTDEBT', 0, 1.),
    MapItem('NetForeignCurrencyExchangeGainLoss', 'CAS', 'NFCEGL', 0, 1.),
    MapItem('NetIncome', 'INC', 'NETINC', 0, 1.),
    MapItem('NetIncomeCommonStockholders', 'INC', 'NICCST', 0, 1.),
    MapItem('NetIncomeContinuousOperations', 'INC', 'NICNOP', 0, 1.),
    MapItem('NetIncomeDiscontinuousOperations', 'INC', 'NIDNOP', 0, 1.),
    MapItem('NetIncomeExtraordinary', 'INC', 'NIEXTR', 0, 1.),
    MapItem('NetIncomeFromContinuingAndDiscontinuedOperation', 'INC', 'NICDOP', 0, 1.),
    MapItem('NetIncomeFromContinuingOperationNetMinorityInterest', 'INC', 'NICOMI', 0, 1.),
    MapItem('NetIncomeFromContinuingOperations', 'CAS', 'NIFCOP', 0, 1.),
    MapItem('NetIncomeFromTaxLossCarryforward', 'INC', 'NITLCF', 0, 1.),
    MapItem('NetIncomeIncludingNoncontrollingInterests', 'INC', 'NIINCI', 0, 1.),
    MapItem('NetIntangiblesPurchaseAndSale', 'CAS', 'NGPRSL', 0, 1.),
    MapItem('NetInterestIncome', 'INC', 'NTNTIN', 0, 1.),
    MapItem('NetInvestmentPropertiesPurchaseAndSale', 'CAS', 'NVPPSL', 0, 1.),
    MapItem('NetInvestmentPurchaseAndSale', 'CAS', 'NVPUSL', 0, 1.),
    MapItem('NetIssuancePaymentsOfDebt', 'CAS', 'NSPYDB', 0, 1.),
    MapItem('NetLongTermDebtIssuance', 'CAS', 'NLTDIS', 0, 1.),
    MapItem('NetNonOperatingInterestIncomeExpense', 'INC', 'NNOIIE', 0, 1.),
    MapItem('NetOtherFinancingCharges', 'CAS', 'NOTFCH', 0, 1.),
    MapItem('NetOtherInvestingChanges', 'CAS', 'NOTICH', 0, 1.),
    MapItem('NetPPE', 'BAL', 'NETPPE', 0, 1.),
    MapItem('NetPPEPurchaseAndSale', 'CAS', 'NPPEPS', 0, 1.),
    MapItem('NetPreferredStockIssuance', 'CAS', 'NPRSTI', 0, 1.),
    MapItem('NetShortTermDebtIssuance', 'CAS', 'NSTDIS', 0, 1.),
    MapItem('NetTangibleAssets', 'BAL', 'NTGAST', 0, 1.),
    MapItem('NonCurrentAccountsReceivable', 'BAL', 'NCACRV', 0, 1.),
    MapItem('NonCurrentAccruedExpenses', 'BAL', 'NCACEX', 0, 1.),
    MapItem('NonCurrentDeferredAssets', 'BAL', 'NCDFAS', 0, 1.),
    MapItem('NonCurrentDeferredLiabilities', 'BAL', 'NCDFLB', 0, 1.),
    MapItem('NonCurrentDeferredRevenue', 'BAL', 'NCDFRE', 0, 1.),
    MapItem('NonCurrentDeferredTaxesAssets', 'BAL', 'NCDFTA', 0, 1.),
    MapItem('NonCurrentDeferredTaxesLiabilities', 'BAL', 'NCDFTL', 0, 1.),
    MapItem('NonCurrentNoteReceivables', 'BAL', 'NCNREC', 0, 1.),
    MapItem('NonCurrentPensionAndOtherPostretirementBenefitPlans', 'BAL', 'NCPOPB', 0, 1.),
    MapItem('NonCurrentPrepaidAssets', 'BAL', 'NCPPAS', 0, 1.),
    MapItem('NormalizedBasicEPS', 'INC', 'NMBEPS', 0, 1.),
    MapItem('NormalizedDilutedEPS', 'INC', 'NMDEPS', 0, 1.),
    MapItem('NormalizedEBITDA', 'INC', 'NEITDA', 0, 1.),
    MapItem('NormalizedIncome', 'INC', 'NMINCM', 0, 1.),
    MapItem('NotesReceivable', 'BAL', 'NTRECV', 0, 1.),
    MapItem('OperatingCashFlow', 'CAS', 'OPCHFW', 0, 1.),
    MapItem('OperatingExpense', 'INC', 'OPEXPS', 0, 1.),
    MapItem('OperatingGainsLosses', 'CAS', 'OPGALO', 0, 1.),
    MapItem('OperatingIncome', 'INC', 'OPINCM', 0, 1.),
    MapItem('OperatingRevenue', 'INC', 'OPREVN', 0, 1.),
    MapItem('OrdinarySharesNumber', 'BAL', 'ODSHNM', 0, 1.),
    MapItem('OtherCapitalStock', 'BAL', 'OHCPSK', 0, 1.),
    MapItem('OtherCashAdjustmentInsideChangeinCash', 'CAS', 'OCAICC', 0, 1.),
    MapItem('OtherCashAdjustmentOutsideChangeinCash', 'CAS', 'OCAOCC', 0, 1.),
    MapItem('OtherCashPaymentsfromOperatingActivities', 'CAS', 'OCPFOA', 0, 1.),
    MapItem('OtherCashReceiptsfromOperatingActivities', 'CAS', 'OCRFOA', 0, 1.),
    MapItem('OtherCurrentAssets', 'BAL', 'OHCUAS', 0, 1.),
    MapItem('OtherCurrentBorrowings', 'BAL', 'OHCUBR', 0, 1.),
    MapItem('OtherCurrentLiabilities', 'BAL', 'OHCULB', 0, 1.),
    MapItem('OtherEquityAdjustments', 'BAL', 'OHEQAD', 0, 1.),
    MapItem('OtherEquityInterest', 'BAL', 'OHEQIN', 0, 1.),
    MapItem('OtherGandA', 'INC', 'OTHGAA', 0, 1.),
    MapItem('OtherIncomeExpense', 'INC', 'OHINEX', 0, 1.),
    MapItem('OtherIntangibleAssets', 'BAL', 'OHINAS', 0, 1.),
    MapItem('OtherInventories', 'BAL', 'OHINVT', 0, 1.),
    MapItem('OtherInvestments', 'BAL', 'OHINVS', 0, 1.),
    MapItem('OtherNonCashItems', 'CAS', 'OHNCIT', 0, 1.),
    MapItem('OtherNonCurrentAssets', 'BAL', 'OHNCAS', 0, 1.),
    MapItem('OtherNonCurrentLiabilities', 'BAL', 'OHNCLB', 0, 1.),
    MapItem('OtherNonOperatingIncomeExpenses', 'INC', 'OHNOIE', 0, 1.),
    MapItem('OtherOperatingExpenses', 'INC', 'OHOPEX', 0, 1.),
    MapItem('OtherPayable', 'BAL', 'OHPAYB', 0, 1.),
    MapItem('OtherProperties', 'BAL', 'OHPROP', 0, 1.),
    MapItem('OtherReceivables', 'BAL', 'OHRECV', 0, 1.),
    MapItem('OtherShortTermInvestments', 'BAL', 'OHSTIV', 0, 1.),
    MapItem('OtherSpecialCharges', 'INC', 'OHSPCH', 0, 1.),
    MapItem('OtherTaxes', 'INC', 'OHTAXS', 0, 1.),
    MapItem('OtherunderPreferredStockDividend', 'INC', 'OHUPSD', 0, 1.),
    MapItem('Payables', 'BAL', 'PAYBLS', 0, 1.),
    MapItem('PayablesAndAccruedExpenses', 'BAL', 'PYAEXP', 0, 1.),
    MapItem('PaymentsonBehalfofEmployees', 'CAS', 'PYOBEM', 0, 1.),
    MapItem('PaymentstoSuppliersforGoodsandServices', 'CAS', 'PYSPGS', 0, 1.),
    MapItem('PbRatio', 'TS', 'PBRTIO', 0, 1.),
    MapItem('PegRatio', 'TS', 'PEGRTO', 0, 1.),
    MapItem('PensionAndEmployeeBenefitExpense', 'CAS', 'PEBNEX', 0, 1.),
    MapItem('PensionandOtherPostRetirementBenefitPlansCurrent', 'BAL', 'POPRBP', 0, 1.),
    MapItem('PeRatio', 'TS', 'PERTIO', 0, 1.),
    MapItem('PolicyAcquisitionExpense', 'TS', 'XXXXXX', 0, 1.),
    MapItem('PreferredSecuritiesOutsideStockEquity', 'BAL', 'PRSOSE', 0, 1.),
    MapItem('PreferredSharesNumber', 'BAL', 'PRSHNM', 0, 1.),
    MapItem('PreferredStock', 'BAL', 'PRSTCK', 0, 1.),
    MapItem('PreferredStockDividendPaid', 'CAS', 'PRSKDP', 0, 1.),
    MapItem('PreferredStockDividends', 'INC', 'PRSKDV', 0, 1.),
    MapItem('PreferredStockEquity', 'BAL', 'PRSKEQ', 0, 1.),
    MapItem('PreferredStockIssuance', 'CAS', 'PRSKIS', 0, 1.),
    MapItem('PreferredStockPayments', 'CAS', 'PRSKPY', 0, 1.),
    MapItem('PrepaidAssets', 'BAL', 'PPDAST', 0, 1.),
    MapItem('PretaxIncome', 'INC', 'PTXINC', 0, 1.),
    MapItem('ProceedsFromStockOptionExercised', 'CAS', 'PFSOEX', 0, 1.),
    MapItem('Properties', 'BAL', 'PROPTS', 0, 1.),
    MapItem('ProvisionandWriteOffofAssets', 'CAS', 'PAWOOA', 0, 1.),
    MapItem('ProvisionForDoubtfulAccounts', 'INC', 'PFDBAC', 0, 1.),
    MapItem('PsRatio', 'TS', 'PSRTIO', 0, 1.),
    MapItem('PurchaseOfBusiness', 'CAS', 'PRCBUS', 0, 1.),
    MapItem('PurchaseOfIntangibles', 'CAS', 'PRCINT', 0, 1.),
    MapItem('PurchaseOfInvestment', 'CAS', 'PRCINV', 0, 1.),
    MapItem('PurchaseOfInvestmentProperties', 'CAS', 'PRCIVP', 0, 1.),
    MapItem('PurchaseOfPPE', 'CAS', 'PRCPPE', 0, 1.),
    MapItem('RawMaterials', 'BAL', 'RAWMAT', 0, 1.),
    MapItem('ReceiptsfromCustomers', 'CAS', 'RECCST', 0, 1.),
    MapItem('ReceiptsfromGovernmentGrants', 'CAS', 'RECGVG', 0, 1.),
    MapItem('Receivables', 'BAL', 'RECVBL', 0, 1.),
    MapItem('ReceivablesAdjustmentsAllowances', 'BAL', 'READAW', 0, 1.),
    MapItem('ReconciledCostOfRevenue', 'INC', 'RCCSRV', 0, 1.),
    MapItem('ReconciledDepreciation', 'INC', 'RCDEPR', 0, 1.),
    MapItem('RentAndLandingFees', 'INC', 'RLFEES', 0, 1.),
    MapItem('RentExpenseSupplemental', 'INC', 'REXSUP', 0, 1.),
    MapItem('RepaymentOfDebt', 'CAS', 'RPYDBT', 0, 1.),
    MapItem('ReportedNormalizedBasicEPS', 'INC', 'RNBEPS', 0, 1.),
    MapItem('ReportedNormalizedDilutedEPS', 'INC', 'RNDEPS', 0, 1.),
    MapItem('RepurchaseOfCapitalStock', 'CAS', 'PCCPSK', 0, 1.),
    MapItem('ResearchAndDevelopment', 'INC', 'RESDEV', 0, 1.),
    MapItem('RestrictedCash', 'BAL', 'RESCSH', 0, 1.),
    MapItem('RestrictedCommonStock', 'BAL', 'RESCSK', 0, 1.),
    MapItem('RestructuringAndMergernAcquisition', 'INC', 'RTMGAQ', 0, 1.),
    MapItem('RetainedEarnings', 'BAL', 'RETEAR', 0, 1.),
    MapItem('SalariesAndWages', 'INC', 'SALWAG', 0, 1.),
    MapItem('SaleOfBusiness', 'CAS', 'SALBUS', 0, 1.),
    MapItem('SaleOfIntangibles', 'CAS', 'SALINT', 0, 1.),
    MapItem('SaleOfInvestment', 'CAS', 'SALINV', 0, 1.),
    MapItem('SaleOfInvestmentProperties', 'CAS', 'SALIVP', 0, 1.),
    MapItem('SaleOfPPE', 'CAS', 'SALPPE', 0, 1.),
    MapItem('SecuritiesAmortization', 'INC', 'SECAMO', 0, 1.),
    MapItem('SellingAndMarketingExpense', 'INC', 'SLMKEX', 0, 1.),
    MapItem('SellingGeneralAndAdministration', 'INC', 'SLGADM', 0, 1.),
    MapItem('ShareIssued', 'BAL', 'SHRISS', 0, 1.),
    MapItem('ShortTermDebtIssuance', 'CAS', 'STDBIS', 0, 1.),
    MapItem('ShortTermDebtPayments', 'CAS', 'STDBPY', 0, 1.),
    MapItem('SpecialIncomeCharges', 'INC', 'SPINCG', 0, 1.),
    MapItem('StockBasedCompensation', 'CAS', 'SKBSCP', 0, 1.),
    MapItem('StockholdersEquity', 'BAL', 'SKHLEQ', 0, 1.),
    MapItem('TangibleBookValue', 'BAL', 'TANGBV', 0, 1.),
    MapItem('TaxEffectOfUnusualItems', 'INC', 'TXEFUI', 0, 1.),
    MapItem('TaxesReceivable', 'BAL', 'TXRECV', 0, 1.),
    MapItem('TaxesRefundPaid', 'CAS', 'TXRFPA', 0, 1.),
    MapItem('TaxesRefundPaidDirect', 'CAS', 'TXRFPD', 0, 1.),
    MapItem('TaxLossCarryforwardBasicEPS', 'INC', 'TLCFBE', 0, 1.),
    MapItem('TaxLossCarryforwardDilutedEPS', 'INC', 'TLCFDE', 0, 1.),
    MapItem('TaxProvision', 'INC', 'TXPROV', 0, 1.),
    MapItem('TaxRateForCalcs', 'INC', 'TXRTCA', 0, 1.),
    MapItem('TotalAssets', 'BAL', 'TOTAST', 0, 1.),
    MapItem('TotalCapitalization', 'BAL', 'TOTCAP', 0, 1.),
    MapItem('TotalDebt', 'BAL', 'TOTDBT', 0, 1.),
    MapItem('TotalEquityGrossMinorityInterest', 'BAL', 'TOTEMI', 0, 1.),
    MapItem('TotalExpenses', 'INC', 'TOTEXP', 0, 1.),
    MapItem('TotalLiabilitiesNetMinorityInterest', 'BAL', 'TOLNMI', 0, 1.),
    MapItem('TotalNonCurrentAssets', 'BAL', 'TOTNCA', 0, 1.),
    MapItem('TotalNonCurrentLiabilitiesNetMinorityInterest', 'BAL', 'TONCLM', 0, 1.),
    MapItem('TotalOperatingIncomeAsReported', 'INC', 'TOOPIR', 0, 1.),
    MapItem('TotalOtherFinanceCost', 'INC', 'TOOHFC', 0, 1.),
    MapItem('TotalPartnershipCapital', 'BAL', 'TOPACA', 0, 1.),
    MapItem('TotalRevenue', 'INC', 'TOREVN', 0, 1.),
    MapItem('TotalTaxPayable', 'BAL', 'TOTXPY', 0, 1.),
    MapItem('TotalUnusualItems', 'INC', 'TOUNIT', 0, 1.),
    MapItem('TotalUnusualItemsExcludingGoodwill', 'INC', 'TOUIEG', 0, 1.),
    MapItem('TradeandOtherPayablesNonCurrent', 'BAL', 'TROPNC', 0, 1.),
    MapItem('TradingSecurities', 'BAL', 'TRSECR', 0, 1.),
    MapItem('TreasurySharesNumber', 'BAL', 'TRSHNM', 0, 1.),
    MapItem('TreasuryStock', 'BAL', 'TRSSTK', 0, 1.),
    MapItem('UnrealizedGainLoss', 'BAL', 'UNGALS', 0, 1.),
    MapItem('UnrealizedGainLossOnInvestmentSecurities', 'CAS', 'UNGLIS', 0, 1.),
    MapItem('WorkingCapital', 'BAL', 'WRKCAP', 0, 1.),
    MapItem('WorkInProcess', 'BAL', 'WRKPRO', 0, 1.),
    MapItem('WriteOff', 'INC', 'WRTOFF', 0, 1.),
    #
    MapItem('CreditCard', 'TS', '', 1, 1.),
    MapItem('CreditLossesProvision', 'TS', '', 1, 1.),
    MapItem('DilutedAverageShares', 'TS', 'DLAVSH', 1, 1.),
    MapItem('FeesAndCommissions', 'TS', '', 1, 1.),
    MapItem('FeesandCommissionExpense', 'TS', '', 1, 1.),
    MapItem('FeesandCommissionIncome', 'TS', '', 1, 1.),
    MapItem('GainLossonSaleofAssets', 'TS', '', 1, 1.),
    MapItem('GrossPremiumsWritten', 'TS', '', 1, 1.),
    MapItem('IncomefromAssociatesandOtherParticipatingInterests', 'TS', '', 1, 1.),
    MapItem('IncreaseDecreaseInNetUnearnedPremiumReserves', 'TS', '', 1, 1.),
    MapItem('InterestExpenseForDeposit', 'TS', '', 1, 1.),
    MapItem('InterestExpenseForLongTermDebtAndCapitalSecurities', 'TS', '', 1, 1.),
    MapItem('InterestExpenseForShortTermDebt', 'TS', '', 1, 1.),
    MapItem('InterestIncomeAfterProvisionForLoanLoss', 'TS', '', 1, 1.),
    MapItem('InterestIncomeFromFederalFundsSoldAndSecuritiesPurchaseUnderAgreementsToResell', 'TS', '', 1, 1.),
    MapItem('InterestIncomeFromLoans', 'TS', '', 1, 1.),
    MapItem('InterestIncomeFromLoansAndLease', 'TS', '', 1, 1.),
    MapItem('InterestIncomeFromSecurities', 'TS', '', 1, 1.),
    MapItem('InvestmentBankingProfit', 'TS', '', 1, 1.),
    MapItem('NetInvestmentIncome', 'TS', '', 1, 1.),
    MapItem('NetPolicyholderBenefitsAndClaims', 'TS', '', 1, 1.),
    MapItem('NetPremiumsWritten', 'TS', '', 1, 1.),
    MapItem('NetRealizedGainLossOnInvestments', 'TS', '', 1, 1.),
    MapItem('NonInterestExpense', 'TS', '', 1, 1.),
    MapItem('NonInterestIncome', 'TS', '', 1, 1.),
    MapItem('OccupancyAndEquipment', 'TS', '', 1, 1.),
    MapItem('OtherInterestExpense', 'TS', '', 1, 1.),
    MapItem('OtherInterestIncome', 'TS', '', 1, 1.),
    MapItem('OtherNonInterestExpense', 'TS', '', 1, 1.),
    MapItem('OtherNonInterestIncome', 'TS', '', 1, 1.),
    MapItem('ProfessionalExpenseAndContractServicesExpense', 'TS', '', 1, 1.),
    MapItem('SecuritiesActivities', 'TS', '', 1, 1.),
    MapItem('ServiceChargeOnDepositorAccounts', 'TS', '', 1, 1.),
    MapItem('TotalMoneyMarketInvestments', 'TS', '', 1, 1.),
    MapItem('TotalPremiumsEarned', 'TS', '', 1, 1.),
    MapItem('TradingGainLoss', 'TS', '', 1, 1.),
    MapItem('TrustFeesbyCommissions', 'TS', '', 1, 1.),
    MapItem('InterestExpenseForFederalFundsSoldAndSecuritiesPurchaseUnderAgreementsToResell', 'TS', '', 1, 1.),
    MapItem('OtherCostofRevenue', 'TS', '', 1, 1.),
    MapItem('CededPremiums', 'TS', '', 1, 1.),
    MapItem('FuelAndPurchasePower', 'TS', '', 1, 1.),
    MapItem('GainonSaleofLoans', 'TS', '', 1, 1.),
    MapItem('OtherCustomerServices', 'TS', '', 1, 1.),
    MapItem('DDACostofRevenue', 'TS', '', 1, 1.),
    MapItem('OperationAndMaintenance', 'TS', '', 1, 1.),
    MapItem('RentandLandingFeesCostofRevenue', 'TS', '', 1, 1.),
    MapItem('LossonExtinguishmentofDebt', 'TS', '', 1, 1.),
    MapItem('EPSestimate', 'TS', '', 1, 1.),
    MapItem('earnings', 'TS', '', 1, 1.),
    MapItem('Fuel', 'TS', '', 1, 1.),
    MapItem('InterestIncomeFromLeases', 'TS', '', 1, 1.),
    MapItem('ExplorationDevelopmentAndMineralPropertyLeaseExpenses', 'TS', '', 1, 1.),
    MapItem('InterestIncomeFromDeposits', 'TS', '', 1, 1.),
    MapItem('MaintenanceAndRepairs', 'TS', '', 1, 1.),
    MapItem('EPSactual', 'TS', '', 1, 1.),
    MapItem('GainonSaleofInvestmentProperty', 'TS', '', 1, 1.),
    MapItem('Equipment', 'TS', '', 1, 1.),
    MapItem('DividendIncome', 'TS', '', 1, 1.),
    MapItem('NetOccupancyExpense', 'TS', '', 1, 1.),
    MapItem('ForeignExchangeTradingGains', 'TS', '', 1, 1.),
    #
    # Old stuff
    #
    MapItem('researchDevelopment', 'INC', 'RESDEV', 1, 1.),
    MapItem('effectOfAccountingCharges', 'INC', 'EEXRCH', 1, 1.),
    MapItem('incomeBeforeTax', 'INC', 'PTXINC', 1, 1.),
    MapItem('minorityInterest', 'INC', 'MININI', 1, 1.),
    MapItem('netIncome', 'INC', 'NETINC', 1, 1.),
    MapItem('sellingGeneralAdministrative', 'INC', 'SLGADM', 1, 1.),
    MapItem('grossProfit', 'INC', 'GSSPFT', 1, 1.),
    MapItem('otherOperatingExpenses', 'INC', 'OHOPEX', 1, 1.),
    MapItem('interestExpense', 'INC', 'INTEXP', 1, 1.),
    MapItem('incomeTaxExpense', 'INC', 'TXPROV', 1, 1.),
    MapItem('totalRevenue', 'INC', 'TOREVN', 1, 1.),
    MapItem('totalOperatingExpenses', 'INC', 'TOTEXP', 1, 1.),
    MapItem('costOfRevenue', 'INC', 'CSTREV', 1, 1.),
    MapItem('totalOtherIncomeExpenseNet', 'INC', 'OHOPEX', 1, 1.),
    MapItem('netIncomeApplicableToCommonShares', 'INC', 'NICCST', 1, 1.),
    MapItem('totalLiab', 'BAL', 'TOLIAB', 1, 1.),
    MapItem('totalStockholderEquity', 'BAL', 'SKHLEQ', 1, 1.),
    MapItem('otherCurrentLiab', 'BAL', 'OHCULB', 1, 1.),
    MapItem('totalAssets', 'BAL', 'TOTAST', 1, 1.),
    MapItem('otherCurrentAssets', 'BAL', 'OHCUAS', 1, 1.),
    MapItem('retainedEarnings', 'BAL', 'RETEAR', 1, 1.),
    MapItem('minorityInterest', 'BAL', 'MININB', 1, 1.),
    MapItem('goodWill', 'BAL', 'GDWILL', 1, 1.),
    MapItem('treasuryStock', 'BAL', 'TRSSTK', 1, 1.),
    MapItem('otherAssets', 'BAL', 'OTHAST', 1, 1.),
    MapItem('cash', 'BAL', 'CHCHEQ', 1, 1.),
    MapItem('totalCurrentLiabilities', 'BAL', 'CULIAB', 1, 1.),
    MapItem('propertyPlantEquipment', 'BAL', 'NETPPE', 1, 1.),
    MapItem('totalCurrentAssets', 'BAL', 'CUASST', 1, 1.),
    MapItem('netTangibleAssets', 'BAL', 'NTGAST', 1, 1.),
    MapItem('shortTermInvestments', 'BAL', 'OHSTIV', 1, 1.),
    MapItem('netReceivables', 'BAL', 'RECVBL', 1, 1.),
    MapItem('longTermDebt', 'BAL', 'LTDEBT', 1, 1.),
    MapItem('inventory', 'BAL', 'IVTORY', 1, 1.),
    MapItem('accountsPayable', 'BAL', 'ACCPAY', 1, 1.),
    MapItem('totalCashflowsFromInvestingActivities', 'CAS', 'CFWINA', 1, 1.),
    MapItem('netBorrowings', 'CAS', 'NISDBT', 1, 1.),
    MapItem('totalCashFromFinancingActivities', 'CAS', 'CFWFIA', 1, 1.),
    MapItem('changeInCash', 'CAS', 'CHCSAR', 1, 1.),
    MapItem('effectOfExchangeRate', 'CAS', 'EEXRCH', 1, 1.),
    MapItem('totalCashFromOperatingActivities', 'CAS', 'CFWOPA', 1, 1.),
    MapItem('depreciation', 'CAS', 'DEPREC', 1, 1.),
    MapItem('dividendsPaid', 'CAS', 'CHDIVP', 1, 1.),
    MapItem('changeToInventory', 'CAS', 'CHINVT', 1, 1.),
    MapItem('changeToAccountReceivables', 'CAS', 'CHACRC', 1, 1.),
    MapItem('capitalExpenditures', 'CAS', 'CAPEXP', 1, 1.),
    MapItem('issuanceOfStock', 'CAS', 'EEXRCH', 1, 1.),
]

YahooFinancialsDownloadList = [
    'AccountsPayable', 'AccountsReceivable', 'AccruedInterestReceivable', 'AccumulatedDepreciation',
    'AdditionalPaidInCapital', 'AdjustedGeographySegmentData', 'AllowanceForDoubtfulAccountsReceivable', 'Amortization',
    'AmortizationCashFlow', 'AmortizationOfIntangibles', 'AmortizationOfIntangiblesIncomeStatement',
    'AmortizationOfSecurities', 'AssetImpairmentCharge', 'AssetsHeldForSaleCurrent', 'AvailableForSaleSecurities',
    'AverageDilutionEarnings', 'BasicAccountingChange', 'BasicAverageShares', 'BasicContinuousOperations',
    'BasicDiscontinuousOperations', 'BasicEPS', 'BasicEPSOtherGainsLosses', 'BasicExtraordinary',
    'BeginningCashPosition', 'BuildingsAndImprovements', 'CapitalExpenditure', 'CapitalExpenditureReported',
    'CapitalLeaseObligations', 'CapitalStock', 'CashAndCashEquivalents', 'CashCashEquivalentsAndShortTermInvestments',
    'CashDividendsPaid', 'CashEquivalents', 'CashFinancial', 'CashFlowFromContinuingFinancingActivities',
    'CashFlowFromContinuingInvestingActivities', 'CashFlowFromContinuingOperatingActivities',
    'CashFlowFromDiscontinuedOperation', 'CashFlowsfromusedinOperatingActivitiesDirect',
    'CashFromDiscontinuedFinancingActivities', 'CashFromDiscontinuedInvestingActivities',
    'CashFromDiscontinuedOperatingActivities', 'CededPremiums', 'ChangeInAccountPayable', 'ChangeInAccruedExpense',
    'ChangeInCashSupplementalAsReported', 'ChangeInDividendPayable', 'ChangeInIncomeTaxPayable',
    'ChangeInInterestPayable', 'ChangeInInventory', 'ChangeInOtherCurrentAssets', 'ChangeInOtherCurrentLiabilities',
    'ChangeInOtherWorkingCapital', 'ChangeInPayable', 'ChangeInPayablesAndAccruedExpense', 'ChangeInPrepaidAssets',
    'ChangeInReceivables', 'ChangeInTaxPayable', 'ChangeInWorkingCapital', 'ChangesInAccountReceivables',
    'ChangesInCash', 'ClassesofCashPayments', 'ClassesofCashReceiptsfromOperatingActivities', 'CommercialPaper',
    'CommonStock', 'CommonStockDividendPaid', 'CommonStockEquity', 'CommonStockIssuance', 'CommonStockPayments',
    'ConstructionInProgress', 'ContinuingAndDiscontinuedBasicEPS', 'ContinuingAndDiscontinuedDilutedEPS',
    'CostOfRevenue', 'CreditCard', 'CreditLossesProvision', 'CurrentAccruedExpenses', 'CurrentAssets',
    'CurrentCapitalLeaseObligation', 'CurrentDebt', 'CurrentDebtAndCapitalLeaseObligation', 'CurrentDeferredAssets',
    'CurrentDeferredLiabilities', 'CurrentDeferredRevenue', 'CurrentDeferredTaxesAssets',
    'CurrentDeferredTaxesLiabilities', 'CurrentLiabilities', 'CurrentNotesPayable', 'CurrentProvisions',
    'DDACostofRevenue', 'DeferredIncomeTax', 'DeferredTax', 'DefinedPensionBenefit', 'Depletion',
    'DepletionIncomeStatement', 'Depreciation', 'DepreciationAmortizationDepletion',
    'DepreciationAmortizationDepletionIncomeStatement', 'DepreciationAndAmortization',
    'DepreciationAndAmortizationInIncomeStatement', 'DepreciationIncomeStatement', 'DerivativeProductLiabilities',
    'DilutedAccountingChange', 'DilutedAverageShares', 'DilutedContinuousOperations', 'DilutedDiscontinuousOperations',
    'DilutedEPS', 'DilutedEPSOtherGainsLosses', 'DilutedExtraordinary', 'DilutedNIAvailtoComStockholders',
    'DividendIncome', 'DividendPaidCFO', 'DividendPerShare', 'DividendReceivedCFO', 'DividendsPaidDirect',
    'DividendsPayable', 'DividendsReceivedCFI', 'DividendsReceivedDirect', 'DomesticSales',
    'DuefromRelatedPartiesCurrent', 'DuefromRelatedPartiesNonCurrent', 'DuetoRelatedPartiesCurrent',
    'DuetoRelatedPartiesNonCurrent', 'EBIT', 'EBITDA', 'EPSactual', 'EPSestimate', 'EarningsFromEquityInterest',
    'EarningsFromEquityInterestNetOfTax', 'EarningsLossesFromEquityInvestments', 'EffectOfExchangeRateChanges',
    'EmployeeBenefits', 'EndCashPosition', 'EnterpriseValue', 'EnterprisesValueEBITDARatio',
    'EnterprisesValueRevenueRatio', 'Equipment', 'ExcessTaxBenefitFromStockBasedCompensation', 'ExciseTaxes',
    'ExplorationDevelopmentAndMineralPropertyLeaseExpenses', 'FeesAndCommissions', 'FeesandCommissionExpense',
    'FeesandCommissionIncome', 'FinancialAssets', 'FinancialAssetsDesignatedasFairValueThroughProfitorLossTotal',
    'FinancingCashFlow', 'FinishedGoods', 'FixedAssetsRevaluationReserve', 'ForeignCurrencyTranslationAdjustments',
    'ForeignExchangeTradingGains', 'ForeignSales', 'ForwardPeRatio', 'FreeCashFlow', 'Fuel', 'FuelAndPurchasePower',
    'GainLossOnInvestmentSecurities', 'GainLossOnSaleOfBusiness', 'GainLossOnSaleOfPPE', 'GainLossonSaleofAssets',
    'GainOnSaleOfBusiness', 'GainOnSaleOfPPE', 'GainOnSaleOfSecurity', 'GainonSaleofInvestmentProperty',
    'GainonSaleofLoans', 'GainsLossesNotAffectingRetainedEarnings', 'GeneralAndAdministrativeExpense',
    'GeneralPartnershipCapital', 'Goodwill', 'GoodwillAndOtherIntangibleAssets', 'GrossAccountsReceivable', 'GrossPPE',
    'GrossPremiumsWritten', 'GrossProfit', 'HedgingAssetsCurrent', 'HeldToMaturitySecurities',
    'ImpairmentOfCapitalAssets', 'IncomeTaxPaidSupplementalData', 'IncomeTaxPayable',
    'IncomefromAssociatesandOtherParticipatingInterests', 'IncreaseDecreaseInNetUnearnedPremiumReserves',
    'InsuranceAndClaims', 'InterestExpense', 'InterestExpenseForDeposit',
    'InterestExpenseForFederalFundsSoldAndSecuritiesPurchaseUnderAgreementsToResell',
    'InterestExpenseForLongTermDebtAndCapitalSecurities', 'InterestExpenseForShortTermDebt',
    'InterestExpenseNonOperating', 'InterestIncome', 'InterestIncomeAfterProvisionForLoanLoss',
    'InterestIncomeFromDeposits', 'InterestIncomeFromFederalFundsSoldAndSecuritiesPurchaseUnderAgreementsToResell',
    'InterestIncomeFromLeases', 'InterestIncomeFromLoans', 'InterestIncomeFromLoansAndLease',
    'InterestIncomeFromSecurities', 'InterestIncomeNonOperating', 'InterestPaidCFF', 'InterestPaidCFO',
    'InterestPaidDirect', 'InterestPaidSupplementalData', 'InterestPayable', 'InterestReceivedCFI',
    'InterestReceivedCFO', 'InterestReceivedDirect', 'InventoriesAdjustmentsAllowances', 'Inventory', 'InvestedCapital',
    'InvestingCashFlow', 'InvestmentBankingProfit', 'InvestmentProperties', 'InvestmentinFinancialAssets',
    'InvestmentsAndAdvances', 'InvestmentsInOtherVenturesUnderEquityMethod', 'InvestmentsinAssociatesatCost',
    'InvestmentsinJointVenturesatCost', 'InvestmentsinSubsidiariesatCost', 'IssuanceOfCapitalStock', 'IssuanceOfDebt',
    'LandAndImprovements', 'Leases', 'LiabilitiesHeldforSaleNonCurrent', 'LimitedPartnershipCapital', 'LineOfCredit',
    'LoansReceivable', 'LongTermCapitalLeaseObligation', 'LongTermDebt', 'LongTermDebtAndCapitalLeaseObligation',
    'LongTermDebtIssuance', 'LongTermDebtPayments', 'LongTermEquityInvestment', 'LongTermProvisions',
    'LossonExtinguishmentofDebt', 'MachineryFurnitureEquipment', 'MaintenanceAndRepairs', 'MarketCap',
    'MinimumPensionLiabilities', 'MinorityInterest', 'MinorityInterests', 'NetBusinessPurchaseAndSale',
    'NetCommonStockIssuance', 'NetDebt', 'NetForeignCurrencyExchangeGainLoss', 'NetIncome',
    'NetIncomeCommonStockholders', 'NetIncomeContinuousOperations', 'NetIncomeDiscontinuousOperations',
    'NetIncomeExtraordinary', 'NetIncomeFromContinuingAndDiscontinuedOperation',
    'NetIncomeFromContinuingOperationNetMinorityInterest', 'NetIncomeFromContinuingOperations',
    'NetIncomeFromTaxLossCarryforward', 'NetIncomeIncludingNoncontrollingInterests', 'NetIntangiblesPurchaseAndSale',
    'NetInterestIncome', 'NetInvestmentIncome', 'NetInvestmentPropertiesPurchaseAndSale',
    'NetInvestmentPurchaseAndSale', 'NetIssuancePaymentsOfDebt', 'NetLongTermDebtIssuance',
    'NetNonOperatingInterestIncomeExpense', 'NetOccupancyExpense', 'NetOtherFinancingCharges',
    'NetOtherInvestingChanges', 'NetPPE', 'NetPPEPurchaseAndSale', 'NetPolicyholderBenefitsAndClaims',
    'NetPreferredStockIssuance', 'NetPremiumsWritten', 'NetRealizedGainLossOnInvestments', 'NetShortTermDebtIssuance',
    'NetTangibleAssets', 'NonCurrentAccountsReceivable', 'NonCurrentAccruedExpenses', 'NonCurrentDeferredAssets',
    'NonCurrentDeferredLiabilities', 'NonCurrentDeferredRevenue', 'NonCurrentDeferredTaxesAssets',
    'NonCurrentDeferredTaxesLiabilities', 'NonCurrentNoteReceivables',
    'NonCurrentPensionAndOtherPostretirementBenefitPlans', 'NonCurrentPrepaidAssets', 'NonInterestExpense',
    'NonInterestIncome', 'NormalizedBasicEPS', 'NormalizedDilutedEPS', 'NormalizedEBITDA', 'NormalizedIncome',
    'NotesReceivable', 'OccupancyAndEquipment', 'OperatingCashFlow', 'OperatingExpense', 'OperatingGainsLosses',
    'OperatingIncome', 'OperatingRevenue', 'OperationAndMaintenance', 'OrdinarySharesNumber', 'OtherCapitalStock',
    'OtherCashAdjustmentInsideChangeinCash', 'OtherCashAdjustmentOutsideChangeinCash',
    'OtherCashPaymentsfromOperatingActivities', 'OtherCashReceiptsfromOperatingActivities', 'OtherCostofRevenue',
    'OtherCurrentAssets', 'OtherCurrentBorrowings', 'OtherCurrentLiabilities', 'OtherCustomerServices',
    'OtherEquityAdjustments', 'OtherEquityInterest', 'OtherGandA', 'OtherIncomeExpense', 'OtherIntangibleAssets',
    'OtherInterestExpense', 'OtherInterestIncome', 'OtherInventories', 'OtherInvestments', 'OtherNonCashItems',
    'OtherNonCurrentAssets', 'OtherNonCurrentLiabilities', 'OtherNonInterestExpense', 'OtherNonInterestIncome',
    'OtherNonOperatingIncomeExpenses', 'OtherOperatingExpenses', 'OtherPayable', 'OtherProperties', 'OtherReceivables',
    'OtherShortTermInvestments', 'OtherSpecialCharges', 'OtherTaxes', 'OtherunderPreferredStockDividend', 'Payables',
    'PayablesAndAccruedExpenses', 'PaymentsonBehalfofEmployees', 'PaymentstoSuppliersforGoodsandServices', 'PbRatio',
    'PeRatio', 'PegRatio', 'PensionAndEmployeeBenefitExpense', 'PensionandOtherPostRetirementBenefitPlansCurrent',
    'PolicyAcquisitionExpense', 'PreferredSecuritiesOutsideStockEquity', 'PreferredSharesNumber', 'PreferredStock',
    'PreferredStockDividendPaid', 'PreferredStockDividends', 'PreferredStockEquity', 'PreferredStockIssuance',
    'PreferredStockPayments', 'PrepaidAssets', 'PretaxIncome', 'ProceedsFromStockOptionExercised',
    'ProfessionalExpenseAndContractServicesExpense', 'Properties', 'ProvisionForDoubtfulAccounts',
    'ProvisionandWriteOffofAssets', 'PsRatio', 'PurchaseOfBusiness', 'PurchaseOfIntangibles', 'PurchaseOfInvestment',
    'PurchaseOfInvestmentProperties', 'PurchaseOfPPE', 'RawMaterials', 'ReceiptsfromCustomers',
    'ReceiptsfromGovernmentGrants', 'Receivables', 'ReceivablesAdjustmentsAllowances', 'ReconciledCostOfRevenue',
    'ReconciledDepreciation', 'RentAndLandingFees', 'RentExpenseSupplemental', 'RentandLandingFeesCostofRevenue',
    'RepaymentOfDebt', 'ReportedNormalizedBasicEPS', 'ReportedNormalizedDilutedEPS', 'RepurchaseOfCapitalStock',
    'ResearchAndDevelopment', 'RestrictedCash', 'RestrictedCommonStock', 'RestructuringAndMergernAcquisition',
    'RetainedEarnings', 'SalariesAndWages', 'SaleOfBusiness', 'SaleOfIntangibles', 'SaleOfInvestment',
    'SaleOfInvestmentProperties', 'SaleOfPPE', 'SecuritiesActivities', 'SecuritiesAmortization',
    'SellingAndMarketingExpense', 'SellingGeneralAndAdministration', 'ServiceChargeOnDepositorAccounts', 'ShareIssued',
    'ShortTermDebtIssuance', 'ShortTermDebtPayments', 'SpecialIncomeCharges', 'StockBasedCompensation',
    'StockholdersEquity', 'TangibleBookValue', 'TaxEffectOfUnusualItems', 'TaxLossCarryforwardBasicEPS',
    'TaxLossCarryforwardDilutedEPS', 'TaxProvision', 'TaxRateForCalcs', 'TaxesReceivable', 'TaxesRefundPaid',
    'TaxesRefundPaidDirect', 'TotalAssets', 'TotalCapitalization', 'TotalDebt', 'TotalEquityGrossMinorityInterest',
    'TotalExpenses', 'TotalLiabilitiesNetMinorityInterest', 'TotalMoneyMarketInvestments', 'TotalNonCurrentAssets',
    'TotalNonCurrentLiabilitiesNetMinorityInterest', 'TotalOperatingIncomeAsReported', 'TotalOtherFinanceCost',
    'TotalPartnershipCapital', 'TotalPremiumsEarned', 'TotalRevenue', 'TotalTaxPayable', 'TotalUnusualItems',
    'TotalUnusualItemsExcludingGoodwill', 'TradeandOtherPayablesNonCurrent', 'TradingGainLoss', 'TradingSecurities',
    'TreasurySharesNumber', 'TreasuryStock', 'TrustFeesbyCommissions', 'UnrealizedGainLoss',
    'UnrealizedGainLossOnInvestmentSecurities', 'WorkInProcess', 'WorkingCapital', 'WriteOff', 'earnings'
]

YahooHistPricesConf = ["date", "open", "high", "low", "close", "adj_close", "volume"]

YahooHistDividendsConf = ["date", "value"]

YahooHistSplitsConf = ["date", "value"]

#
# ECB
#

ECBSeriesConf = ["date", "value", "notes"]

#
# Interactive Brokers
#

IBFinancialsConf = ['ticker', 'freq', 'date', 'currency', 'statement', 'code', 'value']

IBFinancialsMapping = [
    MapItem('AACR', 'BAL', 'ACCREC', 0, 1e6),
    MapItem('ACAE', 'BAL', 'CHCHEQ', 0, 1e6),
    MapItem('ACDB', 'BAL', '', 0, 1e6),
    MapItem('ACSH', 'BAL', '', 0, 1e6),
    MapItem('ADEP', 'BAL', 'ACCDEP', 0, 1e6),
    MapItem('ADPA', 'BAL', '', 0, 1e6),
    MapItem('AGWI', 'BAL', 'GDWILL', 0, 1e6),
    MapItem('AINT', 'BAL', 'OHINAS', 0, 1e6),
    MapItem('AITL', 'BAL', 'IVTORY', 0, 1e6),
    MapItem('ALTR', 'BAL', '', 0, 1e6),
    MapItem('ANTL', 'BAL', '', 0, 1e6),
    MapItem('APPN', 'BAL', 'NETPPE', 0, 1e6),
    MapItem('APPY', 'BAL', 'PPDAST', 0, 1e6),
    MapItem('APRE', 'BAL', '', 0, 1e6),
    MapItem('APTC', 'BAL', 'GSSPPE', 0, 1e6),
    MapItem('ASTI', 'BAL', 'OHSTIV', 0, 1e6),
    MapItem('ATCA', 'BAL', 'CUASST', 0, 1e6),
    MapItem('ATOT', 'BAL', 'TOTAST', 0, 1e6),
    MapItem('ATRC', 'BAL', 'RECVBL', 0, 1e6),
    MapItem('LAEX', 'BAL', '', 0, 1e6),
    MapItem('LAPB', 'BAL', 'ACCPAY', 0, 1e6),
    MapItem('LCLD', 'BAL', '', 0, 1e6),
    MapItem('LCLO', 'BAL', 'CAPLOB', 0, 1e6),
    MapItem('LDBT', 'BAL', '', 0, 1e6),
    MapItem('LLTD', 'BAL', 'LTDEBT', 0, 1e6),
    MapItem('LMIN', 'BAL', 'MININB', 0, 1e6),
    MapItem('LPBA', 'BAL', '', 0, 1e6),
    MapItem('LSTB', 'BAL', '', 0, 1e6),
    MapItem('LSTD', 'BAL', 'STDEBT', 0, 1e6),
    MapItem('LTCL', 'BAL', 'CULIAB', 0, 1e6),
    MapItem('LTLL', 'BAL', 'TOLIAB', 0, 1e6),
    MapItem('LTTD', 'BAL', 'LTDEBT', 0, 1e6),
    MapItem('QEDG', 'BAL', '', 0, 1e6),
    MapItem('QPIC', 'BAL', 'ADDPIC', 0, 1e6),
    MapItem('QRED', 'BAL', 'RETEAR', 0, 1e6),
    MapItem('QTCO', 'BAL', 'ODSHNM', 0, 1e6),
    MapItem('QTEL', 'BAL', 'TOTAST', 0, 1e6),
    MapItem('QTLE', 'BAL', 'SKHLEQ', 0, 1e6),
    MapItem('QTPO', 'BAL', '', 0, 1e6),
    MapItem('QTSC', 'BAL', 'TRSSTK', 0, 1e6),
    MapItem('QUGL', 'BAL', 'UNGALS', 0, 1e6),
    MapItem('SBDT', 'BAL', '', 0, 1e6),
    MapItem('SCMS', 'BAL', 'CSTOCK', 0, 1e6),
    MapItem('SCSI', 'BAL', 'CCESTI', 0, 1e6),
    MapItem('SINV', 'BAL', '', 0, 1e6),
    MapItem('SLTL', 'BAL', '', 0, 1e6),
    MapItem('SOAT', 'BAL', 'OTHAST', 0, 1e6),
    MapItem('SOBL', 'BAL', '', 0, 1e6),
    MapItem('SOCA', 'BAL', 'OHCUAS', 0, 1e6),
    MapItem('SOCL', 'BAL', 'OHCULB', 0, 1e6),
    MapItem('SOEA', 'BAL', '', 0, 1e6),
    MapItem('SOLA', 'BAL', '', 0, 1e6),
    MapItem('SOTE', 'BAL', '', 0, 1e6),
    MapItem('SPOL', 'BAL', '', 0, 1e6),
    MapItem('SPRS', 'BAL', '', 0, 1e6),
    MapItem('SRPR', 'BAL', '', 0, 1e6),
    MapItem('STBP', 'BAL', '', 0, 1e6),
    MapItem('STLD', 'BAL', 'TOTDBT', 0, 1e6),
    MapItem('SUPN', 'BAL', '', 0, 1e6),
    MapItem('FCDP', 'CAS', 'CHDIVP', 0, 1e6),
    MapItem('FPRD', 'CAS', 'NISDBT', 0, 1e6),
    MapItem('FPSS', 'CAS', 'NSTKIS', 0, 1e6),
    MapItem('FTLF', 'CAS', 'CFWFIA', 0, 1e6),
    MapItem('ITLI', 'CAS', 'CFWINA', 0, 1e6),
    MapItem('OBDT', 'CAS', 'DFINTX', 0, 1e6),
    MapItem('ONET', 'CAS', 'NETINC', 0, 1e6),
    MapItem('OTLO', 'CAS', 'OPCHFW', 0, 1e6),
    MapItem('SAMT', 'CAS', 'AMORCF', 0, 1e6),
    MapItem('SCEX', 'CAS', 'CAPEXP', 0, 1e6),
    MapItem('SCIP', 'CAS', '', 0, 1e6),
    MapItem('SCTP', 'CAS', '', 0, 1e6),
    MapItem('SDED', 'CAS', 'DEPREC', 0, 1e6),
    MapItem('SFCF', 'CAS', '', 0, 1e6),
    MapItem('SFEE', 'CAS', 'EEXRCH', 0, 1e6),
    MapItem('SICF', 'CAS', '', 0, 1e6),
    MapItem('SNCC', 'CAS', 'CHCSAR', 0, 1e6),
    MapItem('SNCI', 'CAS', '', 0, 1e6),
    MapItem('SOCF', 'CAS', 'CHWKCP', 0, 1e6),
    MapItem('CEIA', 'INC', '', 0, 1e6),
    MapItem('CGAP', 'INC', '', 0, 1e6),
    MapItem('CIAC', 'INC', 'DLNIAC', 0, 1e6),
    MapItem('CMIN', 'INC', 'MININI', 0, 1e6),
    MapItem('DDPS1', 'INC', 'DVPSHR', 0, 1.),
    MapItem('EDOE', 'INC', '', 0, 1e6),
    MapItem('EIBT', 'INC', 'PTXINC', 0, 1e6),
    MapItem('ELLP', 'INC', '', 0, 1e6),
    MapItem('ENII', 'INC', 'NTNTIN', 0, 1e6),
    MapItem('ERAD', 'INC', 'RESDEV', 0, 1e6),
    MapItem('ETOE', 'INC', 'TOTEXP', 0, 1e6),
    MapItem('NAFC', 'INC', '', 0, 1e6),
    MapItem('NGLA', 'INC', 'GOSPPE', 0, 1e6),
    MapItem('NIBX', 'INC', '', 0, 1e6),
    MapItem('NINC', 'INC', 'NETINC', 0, 1e6),
    MapItem('RNII', 'INC', '', 0, 1e6),
    MapItem('RRGL', 'INC', '', 0, 1e6),
    MapItem('RTLR', 'INC', 'TOREVN', 0, 1e6),
    MapItem('SANI', 'INC', '', 0, 1e6),
    MapItem('SCOR', 'INC', 'CSTREV', 0, 1e6),
    MapItem('SDAJ', 'INC', '', 0, 1e6),
    MapItem('SDBF', 'INC', 'DLDEPS', 0, 1.),
    MapItem('SDNI', 'INC', 'DLNIAC', 0, 1e6),
    MapItem('SDPR', 'INC', 'DPAMIS', 0, 1e6),
    MapItem('SDWS', 'INC', 'DLAVSH', 0, 1e6),
    MapItem('SGRP', 'INC', 'GSSPFT', 0, 1e6),
    MapItem('SIAP', 'INC', '', 0, 1e6),
    MapItem('SIIB', 'INC', 'INTINC', 0, 1e6),
    MapItem('SINN', 'INC', '', 0, 1e6),
    MapItem('SLBA', 'INC', '', 0, 1e6),
    MapItem('SNIE', 'INC', '', 0, 1e6),
    MapItem('SNII', 'INC', '', 0, 1e6),
    MapItem('SNIN', 'INC', '', 0, 1e6),
    MapItem('SONT', 'INC', '', 0, 1e6),
    MapItem('SOOE', 'INC', 'OHOPEX', 0, 1e6),
    MapItem('SOPI', 'INC', 'OPINCM', 0, 1e6),
    MapItem('SORE', 'INC', '', 0, 1e6),
    MapItem('SPRE', 'INC', '', 0, 1e6),
    MapItem('SREV', 'INC', 'TOREVN', 0, 1e6),
    MapItem('SSGA', 'INC', 'SLGADM', 0, 1e6),
    MapItem('STIE', 'INC', 'INTEXP', 0, 1e6),
    MapItem('STXI', 'INC', '', 0, 1e6),
    MapItem('SUIE', 'INC', '', 0, 1e6),
    MapItem('TIAT', 'INC', '', 0, 1e6),
    MapItem('TTAX', 'INC', 'TXPROV', 0, 1e6),
    MapItem('VDES', 'INC', 'NMDEPS', 0, 1e6),
    MapItem('XNIC', 'INC', 'NICCST', 0, 1e6),
]

#
# Nasdaq
#

NasdaqDividendsConf = ['date', 'type', 'amount', 'declaration_date', 'record_date', 'payment_date']
NasdaqPricesConf = ['date', 'close', 'volume', 'open', 'high', 'low']

#
# OECD
#

OECDSeriesConf = [
    "location", "country", "transact_code", "transact", "measure_code",
    "measure", "frequency_code", "frequency", "date_code", "date", "unit_code",
    "unit", "powercode_code", "powercode", "value"
]

#
# Borsa Italiana
#

BorsaItalianaDividendsConf = [
    'type', 'dps_bod', 'dps_agm', 'currency',
    'ex_date', 'payment', 'agm', 'notice'
]

#
# FRED database
#

FREDSeriesConf = [
    'realtime_start', 'realtime_end', 'date', 'value'
]
